// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static class MVC
{
    public static TeacherPouch.Web.Controllers.AdminController Admin = new TeacherPouch.Web.Controllers.T4MVC_AdminController();
    public static TeacherPouch.Web.Controllers.CategoryController Category = new TeacherPouch.Web.Controllers.T4MVC_CategoryController();
    public static TeacherPouch.Web.Controllers.ErrorController Error = new TeacherPouch.Web.Controllers.T4MVC_ErrorController();
    public static TeacherPouch.Web.Controllers.PagesController Pages = new TeacherPouch.Web.Controllers.T4MVC_PagesController();
    public static TeacherPouch.Web.Controllers.PhotosController Photos = new TeacherPouch.Web.Controllers.T4MVC_PhotosController();
    public static TeacherPouch.Web.Controllers.SearchController Search = new TeacherPouch.Web.Controllers.T4MVC_SearchController();
    public static TeacherPouch.Web.Controllers.TagsController Tags = new TeacherPouch.Web.Controllers.T4MVC_TagsController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ViewResult : System.Web.Mvc.ViewResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ViewResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ContentResult : System.Web.Mvc.ContentResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ContentResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}


namespace TeacherPouch.Web.Controllers
{
    public partial class AdminController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController Actions { get { return MVC.Admin; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Admin";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Login = "Login";
            public readonly string Logout = "Logout";
            public readonly string InvokeHttp404 = "InvokeHttp404";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Login = "Login";
            public const string Logout = "Logout";
            public const string InvokeHttp404 = "InvokeHttp404";
        }


        static readonly ActionParamsClass_Login s_params_Login = new ActionParamsClass_Login();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Login LoginParams { get { return s_params_Login; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Login
        {
            public readonly string collection = "collection";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string Login = "Login";
            }
            public readonly string Index = "~/Views/Admin/Index.cshtml";
            public readonly string Login = "~/Views/Admin/Login.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AdminController : TeacherPouch.Web.Controllers.AdminController
    {
        public T4MVC_AdminController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void LoginOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult Login()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Login);
            LoginOverride(callInfo);
            return callInfo;
        }

        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection collection);

        public override System.Web.Mvc.ActionResult Login(System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            LoginOverride(callInfo, collection);
            return callInfo;
        }

        partial void LogoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Logout()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Logout);
            LogoutOverride(callInfo);
            return callInfo;
        }

        partial void InvokeHttp404Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult InvokeHttp404()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.InvokeHttp404);
            InvokeHttp404Override(callInfo);
            return callInfo;
        }

    }
}

namespace TeacherPouch.Web.Controllers
{
    public partial class CategoryController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CategoryController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CategoryController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult CategoryDetails()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CategoryDetails);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CategoryController Actions { get { return MVC.Category; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Category";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Category";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string CategoryDetails = "CategoryDetails";
            public readonly string InvokeHttp404 = "InvokeHttp404";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string CategoryDetails = "CategoryDetails";
            public const string InvokeHttp404 = "InvokeHttp404";
        }


        static readonly ActionParamsClass_CategoryDetails s_params_CategoryDetails = new ActionParamsClass_CategoryDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CategoryDetails CategoryDetailsParams { get { return s_params_CategoryDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CategoryDetails
        {
            public readonly string name = "name";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CelebrationsAndHolidays = "CelebrationsAndHolidays";
                public readonly string Clothing = "Clothing";
                public readonly string Colors = "Colors";
                public readonly string Fall = "Fall";
                public readonly string Flowers = "Flowers";
                public readonly string Food = "Food";
                public readonly string Garden = "Garden";
                public readonly string Math = "Math";
                public readonly string Numbers = "Numbers";
                public readonly string Prepositions = "Prepositions";
                public readonly string School = "School";
                public readonly string Sizes = "Sizes";
                public readonly string Summer = "Summer";
                public readonly string Transportation = "Transportation";
                public readonly string Vacation = "Vacation";
                public readonly string Winter = "Winter";
                public readonly string Zoo = "Zoo";
            }
            public readonly string CelebrationsAndHolidays = "~/Views/Category/CelebrationsAndHolidays.cshtml";
            public readonly string Clothing = "~/Views/Category/Clothing.cshtml";
            public readonly string Colors = "~/Views/Category/Colors.cshtml";
            public readonly string Fall = "~/Views/Category/Fall.cshtml";
            public readonly string Flowers = "~/Views/Category/Flowers.cshtml";
            public readonly string Food = "~/Views/Category/Food.cshtml";
            public readonly string Garden = "~/Views/Category/Garden.cshtml";
            public readonly string Math = "~/Views/Category/Math.cshtml";
            public readonly string Numbers = "~/Views/Category/Numbers.cshtml";
            public readonly string Prepositions = "~/Views/Category/Prepositions.cshtml";
            public readonly string School = "~/Views/Category/School.cshtml";
            public readonly string Sizes = "~/Views/Category/Sizes.cshtml";
            public readonly string Summer = "~/Views/Category/Summer.cshtml";
            public readonly string Transportation = "~/Views/Category/Transportation.cshtml";
            public readonly string Vacation = "~/Views/Category/Vacation.cshtml";
            public readonly string Winter = "~/Views/Category/Winter.cshtml";
            public readonly string Zoo = "~/Views/Category/Zoo.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CategoryController : TeacherPouch.Web.Controllers.CategoryController
    {
        public T4MVC_CategoryController() : base(Dummy.Instance) { }

        partial void CategoryDetailsOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string name);

        public override System.Web.Mvc.ViewResult CategoryDetails(string name)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CategoryDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            CategoryDetailsOverride(callInfo, name);
            return callInfo;
        }

        partial void InvokeHttp404Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult InvokeHttp404()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.InvokeHttp404);
            InvokeHttp404Override(callInfo);
            return callInfo;
        }

    }
}

namespace TeacherPouch.Web.Controllers
{
    public partial class ErrorController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ErrorController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ErrorController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult Error()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Error);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ErrorController Actions { get { return MVC.Error; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Error";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Error";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Http404 = "Http404";
            public readonly string Error = "Error";
            public readonly string InvokeHttp404 = "InvokeHttp404";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Http404 = "Http404";
            public const string Error = "Error";
            public const string InvokeHttp404 = "InvokeHttp404";
        }


        static readonly ActionParamsClass_Error s_params_Error = new ActionParamsClass_Error();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Error ErrorParams { get { return s_params_Error; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Error
        {
            public readonly string httpStatusCode = "httpStatusCode";
            public readonly string exception = "exception";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Error = "Error";
                public readonly string NotFound = "NotFound";
            }
            public readonly string Error = "~/Views/Error/Error.cshtml";
            public readonly string NotFound = "~/Views/Error/NotFound.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ErrorController : TeacherPouch.Web.Controllers.ErrorController
    {
        public T4MVC_ErrorController() : base(Dummy.Instance) { }

        partial void Http404Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult Http404()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Http404);
            Http404Override(callInfo);
            return callInfo;
        }

        partial void ErrorOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int? httpStatusCode, System.Exception exception);

        public override System.Web.Mvc.ViewResult Error(int? httpStatusCode, System.Exception exception)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Error);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "httpStatusCode", httpStatusCode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "exception", exception);
            ErrorOverride(callInfo, httpStatusCode, exception);
            return callInfo;
        }

        partial void InvokeHttp404Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult InvokeHttp404()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.InvokeHttp404);
            InvokeHttp404Override(callInfo);
            return callInfo;
        }

    }
}

namespace TeacherPouch.Web.Controllers
{
    public partial class PagesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PagesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PagesController Actions { get { return MVC.Pages; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Pages";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Pages";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Home = "Home";
            public readonly string About = "About";
            public readonly string Contact = "Contact";
            public readonly string ContactThanks = "ContactThanks";
            public readonly string License = "License";
            public readonly string Sitemap = "Sitemap";
            public readonly string InvokeHttp404 = "InvokeHttp404";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Home = "Home";
            public const string About = "About";
            public const string Contact = "Contact";
            public const string ContactThanks = "ContactThanks";
            public const string License = "License";
            public const string Sitemap = "Sitemap";
            public const string InvokeHttp404 = "InvokeHttp404";
        }


        static readonly ActionParamsClass_Contact s_params_Contact = new ActionParamsClass_Contact();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Contact ContactParams { get { return s_params_Contact; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Contact
        {
            public readonly string submision = "submision";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string About = "About";
                public readonly string Contact = "Contact";
                public readonly string ContactThanks = "ContactThanks";
                public readonly string Home = "Home";
                public readonly string License = "License";
            }
            public readonly string About = "~/Views/Pages/About.cshtml";
            public readonly string Contact = "~/Views/Pages/Contact.cshtml";
            public readonly string ContactThanks = "~/Views/Pages/ContactThanks.cshtml";
            public readonly string Home = "~/Views/Pages/Home.cshtml";
            public readonly string License = "~/Views/Pages/License.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PagesController : TeacherPouch.Web.Controllers.PagesController
    {
        public T4MVC_PagesController() : base(Dummy.Instance) { }

        partial void HomeOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult Home()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Home);
            HomeOverride(callInfo);
            return callInfo;
        }

        partial void AboutOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult About()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.About);
            AboutOverride(callInfo);
            return callInfo;
        }

        partial void ContactOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult Contact()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Contact);
            ContactOverride(callInfo);
            return callInfo;
        }

        partial void ContactOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, TeacherPouch.Models.ContactSubmission submision);

        public override System.Web.Mvc.ActionResult Contact(TeacherPouch.Models.ContactSubmission submision)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Contact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "submision", submision);
            ContactOverride(callInfo, submision);
            return callInfo;
        }

        partial void ContactThanksOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult ContactThanks()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ContactThanks);
            ContactThanksOverride(callInfo);
            return callInfo;
        }

        partial void LicenseOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult License()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.License);
            LicenseOverride(callInfo);
            return callInfo;
        }

        partial void SitemapOverride(T4MVC_System_Web_Mvc_ContentResult callInfo);

        public override System.Web.Mvc.ContentResult Sitemap()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Sitemap);
            SitemapOverride(callInfo);
            return callInfo;
        }

        partial void InvokeHttp404Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult InvokeHttp404()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.InvokeHttp404);
            InvokeHttp404Override(callInfo);
            return callInfo;
        }

    }
}

namespace TeacherPouch.Web.Controllers
{
    public partial class PhotosController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PhotosController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult PhotoDetails()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.PhotoDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult PhotoEdit()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.PhotoEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult PhotoDelete()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.PhotoDelete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PhotoImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PhotoImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PhotoImageDownload()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PhotoImageDownload);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PhotosController Actions { get { return MVC.Photos; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Photos";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Photos";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string PhotoIndex = "PhotoIndex";
            public readonly string PhotoDetails = "PhotoDetails";
            public readonly string PhotoCreate = "PhotoCreate";
            public readonly string PhotoEdit = "PhotoEdit";
            public readonly string PhotoDelete = "PhotoDelete";
            public readonly string PhotoImage = "PhotoImage";
            public readonly string PhotoImageDownload = "PhotoImageDownload";
            public readonly string InvokeHttp404 = "InvokeHttp404";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string PhotoIndex = "PhotoIndex";
            public const string PhotoDetails = "PhotoDetails";
            public const string PhotoCreate = "PhotoCreate";
            public const string PhotoEdit = "PhotoEdit";
            public const string PhotoDelete = "PhotoDelete";
            public const string PhotoImage = "PhotoImage";
            public const string PhotoImageDownload = "PhotoImageDownload";
            public const string InvokeHttp404 = "InvokeHttp404";
        }


        static readonly ActionParamsClass_PhotoDetails s_params_PhotoDetails = new ActionParamsClass_PhotoDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PhotoDetails PhotoDetailsParams { get { return s_params_PhotoDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PhotoDetails
        {
            public readonly string id = "id";
            public readonly string photoName = "photoName";
            public readonly string tag = "tag";
            public readonly string tag2 = "tag2";
        }
        static readonly ActionParamsClass_PhotoCreate s_params_PhotoCreate = new ActionParamsClass_PhotoCreate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PhotoCreate PhotoCreateParams { get { return s_params_PhotoCreate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PhotoCreate
        {
            public readonly string collection = "collection";
        }
        static readonly ActionParamsClass_PhotoEdit s_params_PhotoEdit = new ActionParamsClass_PhotoEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PhotoEdit PhotoEditParams { get { return s_params_PhotoEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PhotoEdit
        {
            public readonly string id = "id";
            public readonly string collection = "collection";
        }
        static readonly ActionParamsClass_PhotoDelete s_params_PhotoDelete = new ActionParamsClass_PhotoDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PhotoDelete PhotoDeleteParams { get { return s_params_PhotoDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PhotoDelete
        {
            public readonly string id = "id";
            public readonly string collection = "collection";
        }
        static readonly ActionParamsClass_PhotoImage s_params_PhotoImage = new ActionParamsClass_PhotoImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PhotoImage PhotoImageParams { get { return s_params_PhotoImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PhotoImage
        {
            public readonly string id = "id";
            public readonly string fileName = "fileName";
        }
        static readonly ActionParamsClass_PhotoImageDownload s_params_PhotoImageDownload = new ActionParamsClass_PhotoImageDownload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PhotoImageDownload PhotoImageDownloadParams { get { return s_params_PhotoImageDownload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PhotoImageDownload
        {
            public readonly string id = "id";
            public readonly string fileName = "fileName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string PhotoCreate = "PhotoCreate";
                public readonly string PhotoDelete = "PhotoDelete";
                public readonly string PhotoDetails = "PhotoDetails";
                public readonly string PhotoEdit = "PhotoEdit";
                public readonly string PhotoIndex = "PhotoIndex";
            }
            public readonly string PhotoCreate = "~/Views/Photos/PhotoCreate.cshtml";
            public readonly string PhotoDelete = "~/Views/Photos/PhotoDelete.cshtml";
            public readonly string PhotoDetails = "~/Views/Photos/PhotoDetails.cshtml";
            public readonly string PhotoEdit = "~/Views/Photos/PhotoEdit.cshtml";
            public readonly string PhotoIndex = "~/Views/Photos/PhotoIndex.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PhotosController : TeacherPouch.Web.Controllers.PhotosController
    {
        public T4MVC_PhotosController() : base(Dummy.Instance) { }

        partial void PhotoIndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult PhotoIndex()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.PhotoIndex);
            PhotoIndexOverride(callInfo);
            return callInfo;
        }

        partial void PhotoDetailsOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int id, string photoName, string tag, string tag2);

        public override System.Web.Mvc.ViewResult PhotoDetails(int id, string photoName, string tag, string tag2)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.PhotoDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "photoName", photoName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tag", tag);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tag2", tag2);
            PhotoDetailsOverride(callInfo, id, photoName, tag, tag2);
            return callInfo;
        }

        partial void PhotoCreateOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult PhotoCreate()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.PhotoCreate);
            PhotoCreateOverride(callInfo);
            return callInfo;
        }

        partial void PhotoCreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection collection);

        public override System.Web.Mvc.ActionResult PhotoCreate(System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PhotoCreate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            PhotoCreateOverride(callInfo, collection);
            return callInfo;
        }

        partial void PhotoEditOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int id);

        public override System.Web.Mvc.ViewResult PhotoEdit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.PhotoEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PhotoEditOverride(callInfo, id);
            return callInfo;
        }

        partial void PhotoEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, System.Web.Mvc.FormCollection collection);

        public override System.Web.Mvc.ActionResult PhotoEdit(int id, System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PhotoEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            PhotoEditOverride(callInfo, id, collection);
            return callInfo;
        }

        partial void PhotoDeleteOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int id);

        public override System.Web.Mvc.ViewResult PhotoDelete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.PhotoDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PhotoDeleteOverride(callInfo, id);
            return callInfo;
        }

        partial void PhotoDeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, System.Web.Mvc.FormCollection collection);

        public override System.Web.Mvc.ActionResult PhotoDelete(int id, System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PhotoDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            PhotoDeleteOverride(callInfo, id, collection);
            return callInfo;
        }

        partial void PhotoImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string fileName);

        public override System.Web.Mvc.ActionResult PhotoImage(int id, string fileName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PhotoImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileName", fileName);
            PhotoImageOverride(callInfo, id, fileName);
            return callInfo;
        }

        partial void PhotoImageDownloadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string fileName);

        public override System.Web.Mvc.ActionResult PhotoImageDownload(int id, string fileName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PhotoImageDownload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileName", fileName);
            PhotoImageDownloadOverride(callInfo, id, fileName);
            return callInfo;
        }

        partial void InvokeHttp404Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult InvokeHttp404()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.InvokeHttp404);
            InvokeHttp404Override(callInfo);
            return callInfo;
        }

    }
}

namespace TeacherPouch.Web.Controllers
{
    public partial class SearchController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SearchController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult Search()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Search);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SearchController Actions { get { return MVC.Search; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Search";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Search";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Search = "Search";
            public readonly string InvokeHttp404 = "InvokeHttp404";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Search = "Search";
            public const string InvokeHttp404 = "InvokeHttp404";
        }


        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string q = "q";
            public readonly string op = "op";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _PhotoThumbnails = "_PhotoThumbnails";
                public readonly string NoneFound = "NoneFound";
                public readonly string SearchResults = "SearchResults";
            }
            public readonly string _PhotoThumbnails = "~/Views/Search/_PhotoThumbnails.cshtml";
            public readonly string NoneFound = "~/Views/Search/NoneFound.cshtml";
            public readonly string SearchResults = "~/Views/Search/SearchResults.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SearchController : TeacherPouch.Web.Controllers.SearchController
    {
        public T4MVC_SearchController() : base(Dummy.Instance) { }

        partial void SearchOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string q, string op);

        public override System.Web.Mvc.ViewResult Search(string q, string op)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "q", q);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "op", op);
            SearchOverride(callInfo, q, op);
            return callInfo;
        }

        partial void InvokeHttp404Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult InvokeHttp404()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.InvokeHttp404);
            InvokeHttp404Override(callInfo);
            return callInfo;
        }

    }
}

namespace TeacherPouch.Web.Controllers
{
    public partial class TagsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TagsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult TagDetails()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.TagDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult TagEdit()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.TagEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult TagDelete()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.TagDelete);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TagsController Actions { get { return MVC.Tags; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Tags";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Tags";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string TagIndex = "TagIndex";
            public readonly string TagDetails = "TagDetails";
            public readonly string TagCreate = "TagCreate";
            public readonly string TagEdit = "TagEdit";
            public readonly string TagDelete = "TagDelete";
            public readonly string InvokeHttp404 = "InvokeHttp404";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string TagIndex = "TagIndex";
            public const string TagDetails = "TagDetails";
            public const string TagCreate = "TagCreate";
            public const string TagEdit = "TagEdit";
            public const string TagDelete = "TagDelete";
            public const string InvokeHttp404 = "InvokeHttp404";
        }


        static readonly ActionParamsClass_TagDetails s_params_TagDetails = new ActionParamsClass_TagDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TagDetails TagDetailsParams { get { return s_params_TagDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TagDetails
        {
            public readonly string tagName = "tagName";
        }
        static readonly ActionParamsClass_TagCreate s_params_TagCreate = new ActionParamsClass_TagCreate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TagCreate TagCreateParams { get { return s_params_TagCreate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TagCreate
        {
            public readonly string collection = "collection";
        }
        static readonly ActionParamsClass_TagEdit s_params_TagEdit = new ActionParamsClass_TagEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TagEdit TagEditParams { get { return s_params_TagEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TagEdit
        {
            public readonly string id = "id";
            public readonly string collection = "collection";
        }
        static readonly ActionParamsClass_TagDelete s_params_TagDelete = new ActionParamsClass_TagDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TagDelete TagDeleteParams { get { return s_params_TagDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TagDelete
        {
            public readonly string id = "id";
            public readonly string collection = "collection";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _FeaturedCategoriesMenu = "_FeaturedCategoriesMenu";
                public readonly string _TagButtons = "_TagButtons";
                public readonly string _TagEditor_Photo = "_TagEditor_Photo";
                public readonly string TagCreate = "TagCreate";
                public readonly string TagDelete = "TagDelete";
                public readonly string TagDetails = "TagDetails";
                public readonly string TagEdit = "TagEdit";
                public readonly string TagIndex = "TagIndex";
            }
            public readonly string _FeaturedCategoriesMenu = "~/Views/Tags/_FeaturedCategoriesMenu.cshtml";
            public readonly string _TagButtons = "~/Views/Tags/_TagButtons.cshtml";
            public readonly string _TagEditor_Photo = "~/Views/Tags/_TagEditor_Photo.cshtml";
            public readonly string TagCreate = "~/Views/Tags/TagCreate.cshtml";
            public readonly string TagDelete = "~/Views/Tags/TagDelete.cshtml";
            public readonly string TagDetails = "~/Views/Tags/TagDetails.cshtml";
            public readonly string TagEdit = "~/Views/Tags/TagEdit.cshtml";
            public readonly string TagIndex = "~/Views/Tags/TagIndex.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TagsController : TeacherPouch.Web.Controllers.TagsController
    {
        public T4MVC_TagsController() : base(Dummy.Instance) { }

        partial void TagIndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult TagIndex()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.TagIndex);
            TagIndexOverride(callInfo);
            return callInfo;
        }

        partial void TagDetailsOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string tagName);

        public override System.Web.Mvc.ViewResult TagDetails(string tagName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.TagDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tagName", tagName);
            TagDetailsOverride(callInfo, tagName);
            return callInfo;
        }

        partial void TagCreateOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult TagCreate()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.TagCreate);
            TagCreateOverride(callInfo);
            return callInfo;
        }

        partial void TagCreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection collection);

        public override System.Web.Mvc.ActionResult TagCreate(System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TagCreate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            TagCreateOverride(callInfo, collection);
            return callInfo;
        }

        partial void TagEditOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int id);

        public override System.Web.Mvc.ViewResult TagEdit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.TagEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            TagEditOverride(callInfo, id);
            return callInfo;
        }

        partial void TagEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, System.Web.Mvc.FormCollection collection);

        public override System.Web.Mvc.ActionResult TagEdit(int id, System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TagEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            TagEditOverride(callInfo, id, collection);
            return callInfo;
        }

        partial void TagDeleteOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int id);

        public override System.Web.Mvc.ViewResult TagDelete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.TagDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            TagDeleteOverride(callInfo, id);
            return callInfo;
        }

        partial void TagDeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, System.Web.Mvc.FormCollection collection);

        public override System.Web.Mvc.ActionResult TagDelete(int id, System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TagDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            TagDeleteOverride(callInfo, id, collection);
            return callInfo;
        }

        partial void InvokeHttp404Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        public override System.Web.Mvc.ViewResult InvokeHttp404()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.InvokeHttp404);
            InvokeHttp404Override(callInfo);
            return callInfo;
        }

    }
}




#endregion T4MVC
#pragma warning restore 1591


