-- This file contains the SQL CREATE TABLE statements which reflect structure of the tables.

CREATE TABLE [Photo] (
    [ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] TEXT NOT NULL COLLATE NOCASE,
    [UniqueID] GUID NOT NULL,
    [IsPrivate] BOOLEAN NOT NULL DEFAULT 0
)

CREATE TABLE [Tag] (
    [ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] TEXT NOT NULL COLLATE NOCASE,
    [IsPrivate] BOOLEAN NOT NULL DEFAULT 0
)

CREATE TABLE [Photo_Tag] (
    [TagID] INTEGER NOT NULL,
    [PhotoID] INTEGER NOT NULL,
    CONSTRAINT [PK_Photo_Tag] PRIMARY KEY ([TagID], [PhotoID])
)

CREATE TABLE [Question] (
    [ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [PhotoID] INTEGER NOT NULL,
    [Text] TEXT NOT NULL COLLATE NOCASE,
    [SentenceStarters] TEXT COLLATE NOCASE,
    [Order] INTEGER
)

CREATE TABLE [QuestionTheme] ( 
    [ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] TEXT NOT NULL COLLATE NOCASE
)

CREATE TABLE [QuestionTheme_Photo] (
    [PhotoID] INTEGER NOT NULL,
    [QuestionThemeID] INTEGER NOT NULL,
    CONSTRAINT [PK_QuestionTheme_Photo] PRIMARY KEY ([PhotoID], [QuestionThemeID])
)